using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Realight_Website.Models
{
	public class Maps
	{
        //Set RoomID (int) !null auto generated by db
        [Display(Name = "MapID")]
        public string MapID { get; set; }

        //Set Title max char 50 !null
        [Display(Name = "Map Name")]
        [MaxLength(24, ErrorMessage = "Invalid Name!")]
        public string mapName { get; set; }

        //Auto generated by db
        [Display(Name = "Date Created")]
        public DateTime? date { get; set; }

        //Set Title max char 50 !null
        [Display(Name = "Map Description")]
        public string description { get; set; }
        
        //Set ImgUrl
        [Display(Name = "List of Map URL")]
        public List<string> mapPreviewURLs { get; set; }

        [Display(Name = "Map File")]
        public List<IFormFile> mapPreviews { get; set; }

        //Set ImgUrl
        [Display(Name = "Download URL")]
        [Range(0, 9999)]
        public string? downloadMapURL { get; set; }

        [Display(Name = "Map Maker")]
        [MaxLength(24, ErrorMessage = "Invalid Name!")]
        [Required]
        public string mapMaker { get; set; }

        [Display(Name = "Map File")]
        [Required]
        public IFormFile mapFile { get; set; }

    }
}
