using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Realight_Website.Models
{
	public class Room
	{
        //Set RoomID (int) !null auto generated by db
        [Display(Name = "RoomID")]
        public int RoomID { get; set; }

        //Set Room Code
        [Display(Name = "Room Code")]
        [Range(0, 9999)]
        public int? RoomCode { get; set; }

        //Set Title max char 50 !null
        [Display(Name = "Room Name")]
        [MaxLength(24, ErrorMessage = "Invalid Name!")]
        [Required]
        public string RoomName { get; set; }

        //Set ImgUrl
        [Display(Name = "ImgURL")]
        [Range(0, 9999)]
        public string? ImgURL { get; set; }

        //Set ImgUrl
        [Display(Name = "Map URL")]
        [Range(0, 9999)]
        public string? MapURL { get; set; }

        //Set player Count
        [Display(Name = "Player Count")]
        [Range(0, 9999)]
        public int? PlayerCount { get; set; }

        [Display(Name = "Room Interest Tags")]
        public List<string> RoomInterestTags { get; set; }
    }
}
